### PR TITLE
Design clause with the way of ufe

### PR DESCRIPTION
**Pull request by yongpingchen**
In this PR, move clauses of internal package to query package. Query clauses is the base clause for trigger clauses 
### Query clauses
- Clause( Mark interface for all clause)
- Equals
- Range
- NotEquals
- And
- Or
- ContainerClause( base class of And/Or)
### Trigger clauses
- AliasClause (Mark interface to represent clause with alias)
- AliasEquals extends `Equals` implements AliasClause( with additional alias) 
- AliasRange extends `Range` implements AliasClause( with additional alias)
Can use AliasEquals/AliasRange with And/Or/NotEquals of query clause to represent the complex clause, since these 2 classes extends `Equals`/`Range`, which is a `Clause`.

### Benefits of this way
- Less the code
- Clauses are easy to understand

### Problem of this way
Trigger clauses can be put into query clause by mistake, see the following snippets

```java
        Clause clause1 = Range.lessThan(
                "currrentTemperature", 
                30);

        AliasRange notAllowedClause = AliasRange.greaterThan(
                "currentTemperature", 
                24, 
                "AirConditionerAlias");
        Clause andClause = new And(clause1, notAllowedClause);
        HistoryStatesQuery query = HistoryStatesQuery
                .Builder
                .newBuilder("AirConditionerAlias")
                .setClause(andClause)
                .setBestEffortLimit(5)
                .build();
```

### CODE REVIEW

**Comment by satoshikumano** [comment]
Did you think about the other possibility?
This design is one of the candidate, but I don't think this is the only one way. There might be another form that avoids the problem raised in this solution.

Here's some question.
- ContainerClause is necessary?
- Why not prepare And/ Or clauses that only takes allowed type.

**Comment by yongpingchen** [comment]
> ContainerClause is necessary?

It provides some common methods for And/Or, so I keep it there. 

> Why not prepare And/ Or clauses that only takes allowed type.

I ever tried to add AliasAnd/AliasOr for trigger condition. Yes, it can solve the problem: put query clause to trigger clause. But can not solve opposite problem: put trigger clause to query clause. Because query clause is the base of trigger clause.

**Comment by satoshikumano** [comment]
> Because query clause is the base of trigger clause.

You can avoid this by removing is-a relation between query clause and trigger clause.

**Comment by yongpingchen** [comment]
> You can avoid this by removing is-a relation between query clause and trigger clause.

Yes. 
That is the way I did in the PR(https://github.com/KiiPlatform/thing-if-AndroidSDK/pull/162). 
Query clause and trigger clause extends/implements from same internal clause, so that they are not parent/child relationship, and can share common structure from internal clause.

**Pull request closed without merging**
