### PR TITLE
Add core package for core class

### PR DESCRIPTION
**Pull request by yongpingchen**
The thing-if-AndroidSDK will be divided into 3 parts: core part APIs, trait part APIs and non-trait part APIs. 

Core part APIs are in `com.kii.thingif.core` package includes the common APIs used by both trait and non-trait APIs. 

The following class are moved into `com.kii.thingif.core` package: 
1. Exception classes
   - BadRequestException
   - ConflictException
   - ForbiddenException
   - GatewayTimeoutException
   - InternalServerErrorException
   - NotFoundException
   - ServiceUnavailableException
   - StoredGatewayAPIInstanceNotFoundException
   - StoredThingIFAPIInstanceNotFoundException
   - ThingIFException
   - ThingIFRestException
   - UnauthorizedException
   - UnsupportedActionException
2. Gateway APIs: which do not concern about trait or non-trait, should be in core part
   - EndNode
   - Gateway
   - GatewayAPI
   - GatewayAPIBuilder
   - GatewayInformation
   - PendingEndNode
3. Utils classes
   - _Log
   - IOUtils
   - JsonUtils
   - Path
   - StringUtils
3. Http request classes
   - IoTRestClient
   - IoTRestRequest
   - OkHttpClientFactory
4. other common used classes by trait/nontrait APIs
   - AbstractThing
   - DataGroupingInterval
   - KiiApp
   - LayoutPosition
   - MediaTypes
   - OnboardEndnodeWithGatewayOptions
   - OnboardWithThingIDOptions
   - OnboardWithVendorThingIDOptions
   - Owner
   - PushBackend
   - ServerError
   - Site
   - StandloneThing
   - Target
   - TargetState
   -  TargetThing
   - TypedID

**Note**
To make this PR easily to be reviewed, the refactoring not include tests, so the tests failed. Tests will be fixed in another PR.

### CODE REVIEW

**Comment by shinsuke-nara** [comment]
I think following package structure is more clear. 

* `com.kii.thingif.core`: Core part of thing if API.
* `com.kii.thingif.nontrait`: Non trait part of thing if API.
* `com.kii.thingif.trait`: Trait part of thing if API.
* `com.kii.thingif.gateway`: Gateway part of thing if API
* `com.kii.thingif.exceptions`: Exceptions for thing if API
* `com.kii.thingif.internal`: Internal use utilities including HTTP.

So 1, 2, 3 and 4 should not be moved to core package, I think.

What do you think?

**Comment by yongpingchen** [comment]
@shinsuke-nara  as expectation, if mobile app use trait+core parts can use trait features, and if mobile app use non-trait+core parts will use non-trait features. 
If done as your suggestion, where should `com.kii.thingif.gateway`, `com.kii.thingif.exceptions` and `com.kii.thingif.internal` be placed? They should not be in trait/non-trait part, should they?

**Comment by shinsuke-nara** [comment]
> The only place is core part.

@yongpingchen I see.

**Comment by yongpingchen** [comment]
@shinsuke-nara just moved these classes to a new package can not satisfy  the purpose. I would like to organise 3 project modules in thing-if-AndroidSDK: core, nontrait and trait. I will open another PR for the new way, and close this PR first.

**Pull request merged**
