### PR TITLE
Improve aggregation functions

### PR DESCRIPTION
**Pull request by yongpingchen**
- Field has been unified.
 - ThingIFAPI#count has been removed.
(reference: [comment on thing-if-ios](https://github.com/KiiPlatform/thing-if-iOSSDK/pull/265#issuecomment-272071283))

### CODE REVIEW

**Comment by shinsuke-nara** [comment]
@yongpingchen

- `Aggregation` constructor is public so we does not require factory methods.
- `Aggregation` constructor should check its argument and throws IllegalArgumentException

What do you think?

**Comment by yongpingchen** [comment]
@shinsuke-nara 
> Aggregation constructor is public so we does not require factory methods.

I can make the constructor private. 

> Aggregation constructor should check its argument and throws IllegalArgumentException

Constructor throws exception is not good practice( according to Kumano-san).  I will make another factory method for it.

**Comment by yongpingchen** [comment]
@shinsuke-nara please check the commit: 32c6bb3
- Make default constructor private
- Add a new factory method `newAggregation` for the case, function type passed as parameter.

**Comment by shinsuke-nara** [comment]
@yongpingchen LGTM!

**Pull request merged**
