### PR TITLE
Support trait design

### PR DESCRIPTION
**Pull request by yongpingchen**
## Brief
From v1.0 trait is mandatory to be used, so the design of v1.0 is based on trait. 

## Main changes
1. Improve Action, TargetState for alias and improve registration of Action and TargetState. Refer to PR: #176 
1. Redesign clauses. Refer to PR: #179 #180 #184 
1. Add history state query APIs(ungrouped, grouped, aggregate): Refer to PR: #188 #172 
1. Add APIs for ThingType/FirmwareVersion. Refer to PR: #167 
1. Add APIs to retrieve target state by alias: #168 (in #176 change the return type) 
1. Remove Schema/SchemaBuilder/GsonRepository. #185

### CODE REVIEW

**Comment by yongpingchen** [comment]
@satoshikumano About the design of clause. The implementation of ufe could not solve the problem of mixing use of query clause and trigger clause(I tried on branch [improve_clause_design](https://github.com/KiiPlatform/thing-if-AndroidSDK/tree/improve_clause_design)). I only can find the way of implementation in this PR can solve the problem.  What do you think?

**Comment by satoshikumano** [comment]
@yongpingchen 
I see. Let's choose #162 as base design.
But I think there's some refinement on #162 

* Let's not put base models into internal package. It should be exposed.
* Using same name for class/ interface in base, query, trigger is confusing.
* It's better make ContainerClause as interface.
* Using Generic interface could brings more clarity.

**Comment by yongpingchen** [comment]
@satoshikumano 

> Using same name for class/ interface in base, query, trigger is confusing.

To use same name, because it also happen in some other java framework, use the same name but in different package.  I agree to use different name to avoid confuse. 

I will refactor based on your comment in another PR.

**Comment by satoshikumano** [comment]
FYI.

Here's my experiment.
https://github.com/KiiPlatform/thing-if-AndroidSDK/commit/bcdc7dfb11a1e56d66a1722366158fb516811ae9

Another approach for providing And/ Or is not present them as Clause but factory class of clause.
Ultimately, We only needs result of toJSONObject().
To achieve this, Concatenating clause only needs each results of toJSONObject().

In this context, the class ConcatenaedClause only implements toJSONObject() and And/ Or factory class will generate the ConcatenaedClause holds a JSONObject that is generated by given Clause's toJSONObject().
(And/ Or class itself no need to be presented as Clause in this way.)

**Comment by satoshikumano** [comment]
Added commits illustrates that and/ or is implemented as factory.

https://github.com/KiiPlatform/thing-if-AndroidSDK/commit/0d0df67facdfd001905217a25f82befc800faef9

**Comment by yongpingchen** [comment]
TODO: 
1. Remove schema, shemeversion. Not only that method, the Schema and SchemaBuilder class also needed to be removed. I will remove them in separate PR, since it will affect a lot of files.
2. Refactor the Builder to make them as inner class. for 
   - ThingIFAPIBuilder
   - GatewayAPIBuilder
3. In iOS, we have decided to merge Count and Aggregation. KiiPlatform/thing-if-iOSSDK/#265
   - Field has been unified.
   - ThingIFAPI#count has been removed.

**Comment by yongpingchen** [comment]
@satoshikumano Fixed by your comment. Please confirm. 
1. Actions > AliasActions, ActionResult > AliasActionResults on commit ab45605
2. Mention about Exception thrown when setting thing type second time on commit  ea3955f
3. Mention about Limitation of time range in query on commit 	76cd535
4. Describe time range is inclusive on commit ea46dd1

**Pull request merged**
