### PR TITLE
Implement patch trigger APIs

### PR DESCRIPTION
**Pull request by yongpingchen**
- Implement patchTrigger APIs
  - ThingIFAPI#patchTrigger(String, TriggeredCommandForm, Predicate, TriggerOptions)
  - ThingIFAPI#patchTrigger(String, ServerCode, Predicate, TriggerOptions)
  - ThingIFAPI#patchTrigger(String, ServerCode, Predicate)
- Add small tests

### CODE REVIEW

**Comment by shinsuke-nara** [comment]
@yongpingchen LGTM but can we remove `patchTriggerWithForm()` and integrate its implementation to `patchTrigger()`?

**Comment by yongpingchen** [comment]
@shinsuke-nara fixed by your comment. Please confirm.

**Comment by shinsuke-nara** [comment]
@yongpingchen I have another question. 

`patchTrigger()` for server code has 2 version. they are trigger option version and non trigger option version.
`patchTrigger()` for command has only one version.

Why is it different?

**Comment by yongpingchen** [comment]
@shinsuke-nara They should be with same pattern. I would like to use the pattern for patchTrigger with ServerCode. So I will add another API ThingIFAPI#patchTrigger(String, TriggeredCommandForm, Predicate). 

Same for ThingIFAPI#postTrigger for command. 

I will do it in another PR.

**Comment by shinsuke-nara** [comment]
@yongpingchen 
> @shinsuke-nara They should be with same pattern. I would like to use the pattern for patchTrigger with ServerCode. So I will add another API ThingIFAPI#patchTrigger(String, TriggeredCommandForm, Predicate).
>
> Same for ThingIFAPI#postTrigger for command.
>
>I will do it in another PR.

It sounds good for me but I'm sorry for my [this comment](https://github.com/KiiPlatform/thing-if-AndroidSDK/pull/245#issuecomment-282936790). we will use `patchTriggerWithFrom()` in new `patchTrigger()` for command. Could you rollback 476c668 ?

If you want to rollback it in another PR or you rollback it in this PR, either is fine for me:)
In either way, Please merge this.

**Comment by yongpingchen** [comment]
@shinsuke-nara 
> It sounds good for me but I'm sorry for my this comment. we will use patchTriggerWithFrom() in new patchTrigger() for command. Could you rollback 476c668 ?

I will do it in another PR.

**Pull request merged**
