### PR TITLE
implement and test ThingIFAPI#updateFirmwareVersion.

### PR DESCRIPTION
**Pull request by naoki-akimoto**
ThingIFAPI#updateFirmwareVersionの実装を行いテストを追加しました。レビューをお願いします。

### CODE REVIEW

**Comment by shinsuke-nara** [comment]
@naoki-akimoto 

Is specification [this](http://docs.kii.com/rest/#thing_management-update_the_thing_information)? If so, LGTM!

**Comment by yongpingchen** [comment]
@naoki-akimoto please use [thing-if REST API](https://docs.google.com/document/edit?hgd=1&id=1iYlAhVKxKN1Xu__DbU1TKs7VxO5Hbcs3vg84KsvndFs#heading=h.gcf1ky2d1hc8) for updating firmware version.

**Comment by shinsuke-nara** [comment]
@yongpingchen 
In #244, We used [this KiiCloud REST API](http://docs.kii.com/rest/#thing_management-get_the_thing_information) to get firmware version. Why do we use [thing-if REST API](https://docs.google.com/document/edit?hgd=1&id=1iYlAhVKxKN1Xu__DbU1TKs7VxO5Hbcs3vg84KsvndFs#heading=h.gcf1ky2d1hc8) for updating firmware version?

I do not opposite your decision but I wonder. I appreciate if you explain it.

**Comment by yongpingchen** [comment]
> In #244, We used this KiiCloud REST API to get firmware version. Why do we use thing-if REST API for updating firmware version?

In #244, since we don't have thing-if REST API for this purpose, so we need to use cloud API. To update firmwareVersion, it is simple to use thing-if REST API and also because it is in thing-if SDK, so thing-if REST API is prefer.

**Comment by shinsuke-nara** [comment]
@yongpingchen Thank you for your answer.

I misunderstood about this. I thought [this thing-if REST API](https://docs.google.com/document/edit?hgd=1&id=1iYlAhVKxKN1Xu__DbU1TKs7VxO5Hbcs3vg84KsvndFs#heading=h.89l3j2b2zsvf) is fine but it gets all firmware versions. This does not match our purpose. Now I understood:+1:

**Comment by yongpingchen** [comment]
@shinsuke-nara  my mistake. There is thing-if REST API for getFirmwareVersion.  https://docs.google.com/document/edit?hgd=1&id=1iYlAhVKxKN1Xu__DbU1TKs7VxO5Hbcs3vg84KsvndFs#heading=h.dqycjv4twts9

So we need to use this API for getFirmwareVersion too.

**Comment by naoki-akimoto** [comment]
@yongpingchen @shinsuke-nara fixed. Please confirm.

**Comment by shinsuke-nara** [comment]
@naoki-akimoto LGTM!

**Pull request merged**
