### PR TITLE
Reconstruct project to 3 modules

### PR DESCRIPTION
**Pull request by yongpingchen**
Divide project into 3 modules: Core, Trait, Nontrait. Core module included by other 2 modules. 

**Why to use module?**
Release trait and nontrait library can be based on modules. Gradle tasks are organised by module, which is clean and clear. 

### Core Module
1. Exception classes
   - BadRequestException
   - ConflictException
   - ForbiddenException
   - GatewayTimeoutException
   - InternalServerErrorException
   - NotFoundException
   - ServiceUnavailableException
   - StoredGatewayAPIInstanceNotFoundException
   - StoredThingIFAPIInstanceNotFoundException
   - ThingIFException
   - ThingIFRestException
   - UnauthorizedException
   - UnsupportedActionException
2. Gateway APIs: which do not concern about trait or non-trait, should be in core part
   - EndNode
   - Gateway
   - GatewayAPI
   - GatewayAPIBuilder
   - GatewayInformation
   - PendingEndNode
   - GsonRepository, used by GatewayAPI
3. Utils classes
   - _Log
   - IOUtils
   - JsonUtils
   - Path
   - StringUtils
3. Http request classes
   - IoTRestClient
   - IoTRestRequest
   - OkHttpClientFactory
4. Used by Command: both by triat formatted command and non trait formatted command
   - CommandState
5. Used by Triggers: both by trait formatted trigger by non trait formatted trigger
   - Clause
     - And
     - Clause
     - ContainerClause
     - NotEquals
     - Or
   - Condition
   - EventSource
   - Predicate
   - ScheduleOncePredicate
   - SchedulePredicate
   - ServerCode
   - StatePredicate
   - TriggeredServerCodeResult
   - TriggerOptions
   - TriggersWhat
   - TriggersWhen
6. other common used classes by trait/nontrait APIs
   - AbstractThing
   - DataGroupingInterval
   - KiiApp
   - LayoutPosition
   - MediaTypes
   - OnboardEndnodeWithGatewayOptions
   - OnboardWithThingIDOptions
   - OnboardWithVendorThingIDOptions
   - Owner
   - PushBackend
   - ServerError
   - Site
   - StandloneThing
   - Target
   - TargetState
   -  TargetThing
   - TypedID
### Nontrait Module
  - ThingIFAPI
  - ThingIFAPIBuilder
  - non trait formatted command
    - Action
    - ActionResult
    - Command
    - CommandForm
   - non trait Clause
     - Equals
     - Range

  - Exception
    - UnsupportedSchemaException
  - Schema
    - Schema
    - SchemaBuilder
  - GsonRepository
### Trait Module
  - TraitThingIFAPI

**Note**
To make this PR easily to be reviewed, the refactoring not include tests, so the tests failed. Tests will be fixed in another PR.

### CODE REVIEW

**Comment by shinsuke-nara** [comment]
@yongpingchen 

I checked the list in description. I have following questions:

  * `TriggeredCommandForm` does not appear in any modules.
  *  In `Clause` section, We should place `Equal` class, `NotEqual` class and `Range` class in each of **Nontrait module** and **Trait module**. We should not place them in **Core module**.

What do you think?

**Comment by yongpingchen** [comment]
> TriggeredCommandForm does not appear in any modules.
It is under Nontrait module now. And in Trait module, I didn't implement yet(I will do it another PR)

> In Clause section, We should place Equal class, NotEqual class and Range class in each of Nontrait module and Trait module. We should not place them in Core module.
Agree.

**Comment by yongpingchen** [comment]
@shinsuke-nara please confirm

**Comment by yongpingchen** [comment]
We decided not to use multiple archives. Close this PR

**Pull request closed without merging**
