### PR TITLE
Separate clause of query from clause of trigger

### PR DESCRIPTION
**Pull request by yongpingchen**
- Move original clause to internal package
- Extends internal clause classes for history state querying
- Extends internal clause classes for condition of trigger

### CODE REVIEW

**Comment by yongpingchen** [comment]
@shinsuke-nara  can you review this PR

**Comment by shinsuke-nara** [comment]
@yongpingchen 

I think we should implement trigger clauses and query clauses without extending internal clause classes.

Trigger clauses and query clauses are different data structure. There is no relationship between trigger clauses and query clauses.

What do you think?

**Comment by yongpingchen** [comment]
@shinsuke-nara query clause and trigger clause are almost the same structure. Only different is the alias.  What I pretend to do is to share the same logic, so I bring the same structure to internal package.

**Comment by shinsuke-nara** [comment]
@yongpingchen I will tell you beforehand that this is my preference :)

> What I pretend to do is to share the same logic, so I bring the same structure to internal package.

Sharing same logic is important but we should share logic only if codes require same logic.

In this case, trigger clauses and query clauses are similar but not same in my opinion. Although it is hard to distinguish `similar` and `same`. One of my criteria is ***If a specification says they are same, we should share same logic***.

Trait rest API specification does not say that trait clauses and query clauses are same. So I prefer to implement trigger clause and query clause independently. I have some concern about using extending as following:

  * If we change trigger clause specification or query clause specification, using extending may inhibit to change these classes.
  * Using extending makes understanding the classes more difficult. In other words, Using extending is not simple.

If you prefer to use extending, It is OK for me. Because this is difference of our preference :)

But if we use extending, we should make internal classes abstract. Developers does not need to construct their classes so we prohibit it.

**Comment by yongpingchen** [comment]
@shinsuke-nara  
> Trait rest API specification does not say that trait clauses and query clauses are same. So I prefer to implement trigger clause and query clause independently.

Yes, there is not specification mentioned about that.  However, we do exactly use the same structure, except `alias`. In this point of view, query clause and trigger clause can be considered as inherit from same supper class. Trigger clause compared with query clause, has a additional filed `alias`.  That is why I think it is better to make internal clause for both of them. 


>But if we use extending, we should make internal classes abstract. Developers does not need to construct their classes so we prohibit it.

Thanks. I agree with this.

**Comment by shinsuke-nara** [comment]
OK

**Pull request merged**
