### PR TITLE
implement and test TimeRange.

### PR DESCRIPTION
**Pull request by naoki-akimoto**
TimeRangeの実装の修正とテストを追加しました、レビューをお願いします。

### CODE REVIEW

**Comment by yongpingchen** [comment]
@naoki-akimoto can you also implement `equals` and `hashCode` methods?

**Comment by shinsuke-nara** [comment]
@naoki-akimoto 
Please adopt @yongpingchen san's comment.

Other than that, LGTM.

**Comment by naoki-akimoto** [comment]
@yongpingchen @shinsuke-nara  fixed. Please confirm.

**Comment by yongpingchen** [comment]
LGTM

**Pull request merged**
